### PR TITLE
Documentation Drive Updates

### PR DESCRIPTION
**Pull request by ike**
- Current documentation: 8
- Seems clear
- A little API documentation -- the API is small tho

New documentation score: 9

### CODE REVIEW

**Comment by ike** [comment]
One question I had -- is the `getState` method part of a standard ssb interop api or something? I can't tell that it's used by any other function in this module.

**Comment by dominictarr** [comment]
oh, no I think getState made it into the public api to make it easier to debug... it returns all the addresses... which could be useful... considering removing it... there is no test coverage for it so I will remove it.

**Comment by dominictarr** [comment]
merged into 1.1.5! thanks!

**Comment by ike** [comment]
Sweet! This was fun.

**Pull request merged**
